import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import { Box } from "@chakra-ui/react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        h="650px"
        backgroundImage={
          "https://imageio.forbes.com/specials-images/imageserve/5e5646e1d2111200062ef3aa/GUI--Graphical-User-Interface--concept-/960x0.jpg"
        }
        backgroundSize="cover"
        backgroundRepeat="no-repeat"
      />
    </>
  );
}
